services:
  stt:
    image: "marcelheisler/jetson_stt:latest"
    ports:
      - "9000:9000"
    environment:
      - ASR_MODEL=base
      - ASR_ENGINE=openai_whisper
    runtime: nvidia
    volumes:
      - type: bind
        source: ${MODELS_PATH}/stt_models/
        target: /root/.cache/whisper
  tts:
    image: "marcelheisler/jetson_tts:latest"
    ports:
      - "7223:7223"
    environment:
      - MODEL_NAME=tts_models/en/vctk/vits
    runtime: nvidia
    volumes:
      - type: bind
        source: ${MODELS_PATH}/tts_models
        target: /root/.local/share/tts/
  lipsync:
    image: "marcelheisler/jetson_lipsync:latest"
    ports:
      - "7222:7222"
    environment:
      - TRANSFORMERS_CACHE=/root/.cache/transformers
      - TRANSFORMERS_OFFLINE=${TRANSFORMERS_OFFLINE-0}
    runtime: nvidia
    volumes:
      - type: bind
        source: ${MODELS_PATH}/lipsync_models
        target: /root/.cache/transformers
